version: 2.1

orbs:
  node: circleci/node@5.1.0

jobs:
  build:
    executor:
      name: node/default
      tag: '18.16'
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run build
          name: Build client

workflows:
  build-workflow:
    jobs:
      - build
